blank_issues_enabled: false
contact_links:
  - name: HACF Discord
    url: https://discord.gg/PaZFEjX
    about: The HACF discord server
  - name: HACF Forums
    url: https://forum.hacf.fr/
    about: The HACF forum